// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQg7nsDlVec_WpZcxatnkiTi18G1UAfU',
    appId: '1:966963231929:web:1a5d591c6829a8f67baf68',
    messagingSenderId: '966963231929',
    projectId: 'auth-37f45',
    authDomain: 'auth-37f45.firebaseapp.com',
    storageBucket: 'auth-37f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWeWD_YeFY-MdLNTqU_VXQvO8RvWKMF4',
    appId: '1:966963231929:android:8785f33fedd21a2d7baf68',
    messagingSenderId: '966963231929',
    projectId: 'auth-37f45',
    storageBucket: 'auth-37f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS6LMQPfRcf2fSe4HU895hUuBX0wu6hus',
    appId: '1:966963231929:ios:fff2257ba45068367baf68',
    messagingSenderId: '966963231929',
    projectId: 'auth-37f45',
    storageBucket: 'auth-37f45.appspot.com',
    androidClientId: '966963231929-5onqlfrt6co078brurj64ab0u9gokigp.apps.googleusercontent.com',
    iosClientId: '966963231929-9guuj7s3e1s87hcpoj2ddttahrnlo5qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS6LMQPfRcf2fSe4HU895hUuBX0wu6hus',
    appId: '1:966963231929:ios:fff2257ba45068367baf68',
    messagingSenderId: '966963231929',
    projectId: 'auth-37f45',
    storageBucket: 'auth-37f45.appspot.com',
    androidClientId: '966963231929-5onqlfrt6co078brurj64ab0u9gokigp.apps.googleusercontent.com',
    iosClientId: '966963231929-9guuj7s3e1s87hcpoj2ddttahrnlo5qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEQg7nsDlVec_WpZcxatnkiTi18G1UAfU',
    appId: '1:966963231929:web:8c0e9a50305a01117baf68',
    messagingSenderId: '966963231929',
    projectId: 'auth-37f45',
    authDomain: 'auth-37f45.firebaseapp.com',
    storageBucket: 'auth-37f45.appspot.com',
  );
}
